set nocompatible              " be iMproved, required

syntax on
filetype plugin on
filetype plugin indent on

set t_Co=256
set backspace=2
set background=dark
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//

" Macbook: copy to system clipboard
if has("clipboard")
  set clipboard=unnamed
endif
